name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Derive function app name
        id: derive
        run: bash .github/scripts/derive-names.sh

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Azure Function App Settings
        uses: azure/cli@v2
        with:
          inlineScript: |
            az functionapp config appsettings set \
              --name ${{ env.FUNCTION_APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --settings \
                "DB_HOST=${{ secrets.DB_HOST }}" \
                "DB_PORT=${{ secrets.DB_PORT }}" \
                "DB_USER=${{ secrets.DB_USER }}" \
                "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
                "DB_NAME=${{ secrets.DB_NAME }}" \
                "VALIDATION_ERROR_THRESHOLD=0.10" \
                "ENABLE_MV_REFRESH=true" \
                "ALERT_EMAIL=${{ secrets.ALERT_EMAIL }}"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: .

      - name: Health check
        env:
          WEB_APP_NAME: ${{ env.FUNCTION_APP_NAME }}
          HEALTHCHECK_PATH: /api/healthz
        run: bash .github/scripts/health-check.sh
